#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := aws_iot_thing_shadow
export IDF_PATH=C:/msys64/home/david/Github/esp-idf
include $(IDF_PATH)/make/project.mk

