#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := thing_code
IDF_PATH=/c/Users/david/Github/esp-idf
include $(IDF_PATH)/make/project.mk

